### ISSUE TITLE
What is the cuda version required by this repo? Can CUDA10 be used

### ISSUE THREAD

**Issue by LeiYangJustin** [jshi31/NAFAE#3]
Hi jshi, thanks for sharing the codes. I found your paper quite interesting and would like to take a look at your codes. However, I use CUDA10. According to the prerequisite you state in the ReadMe, it seems only pytorch0.4.0 can be used; as ffi module has been deprecated in Pytorch>=1.0.0.

Do you have any workaround so that I can run your code with pytorch0.4.0 but using CUDA10 instead?

**Comment by jshi31** [comment]
I tried that, but the current PyTorch version is constraint by the object detector, which can only be compiled with Pytorch <1.0.0. One way is to update the object detector that supports the higher version Pytorch, as suggested in https://github.com/jwyang/faster-rcnn.pytorch. This change could involve a lot of work, so currently I haven't found a good workaround.
